# SPDX-License-Identifier: GPL-2.0

ifeq ($(CONFIG_ARCH_ROCKCHIP), y)

dtb-$(CONFIG_CPU_PX30) += \
	px30-ad-d6-anx6345.dtb \
	px30-ad-r35-mb-rk618-dual-lvds.dtb \
	px30-ad-r35-mb-rk618-hdmi.dtb \
	px30-ad-r35-mb-rk618-hdmi-lvds.dtb \
	px30-ad-r35-mb-rk618-lvds.dtb \
	px30-evb-ddr3-lvds-v10.dtb \
	px30-evb-ddr3-v10.dtb \
	px30-evb-ddr3-v10-avb.dtb \
	px30-evb-ddr3-v10-linux.dtb \
	px30-evb-ddr3-v10-robot-linux.dtb \
	px30-evb-ddr3-v10-robot-no-gpu-linux.dtb \
	px30-evb-ddr3-v11.dtb \
	px30-evb-ddr3-v11-avb.dtb \
	px30-evb-ddr3-v11-linux.dtb \
	px30-evb-ddr4-v10.dtb \
	px30-evb-ext-rk618.dtb \
	px30-evb-ext-rk618-avb.dtb \
	px30-z7-a0-rk618-dsi.dtb \

dtb-$(CONFIG_CPU_RK3326) += \
	rk3326-evb-ai-va-v10.dtb \
	rk3326-evb-ai-va-v11.dtb \
	rk3326-evb-ai-va-v11-i2s-dmic.dtb \
	rk3326-evb-ai-va-v12.dtb \
	rk3326-evb-lp3-v10.dtb \
	rk3326-evb-lp3-v10-avb.dtb \
	rk3326-evb-lp3-v10-linux.dtb \
	rk3326-evb-lp3-v10-robot-linux.dtb \
	rk3326-evb-lp3-v10-robot-no-gpu-linux.dtb \
	rk3326-evb-lp3-v11.dtb \
	rk3326-evb-lp3-v11-avb.dtb \
	rk3326-863-lp3-v10.dtb \
	rk3326-863-lp3-v10-avb.dtb \
	rk3326-863-lp3-v10-rkisp1.dtb \
	rk3326-86v-v10.dtb \

dtb-$(CONFIG_CPU_RK3328) += \
	rk3328-box-liantong.dtb \
	rk3328-box-liantong-avb.dtb \
	rk3328-evb.dtb \
	rk3328-evb-android.dtb \
	rk3328-evb-android-avb.dtb \
	rk3328-rock64.dtb \
	rk3328-rock64-android.dtb \
	rk3328-rock64-android-avb.dtb \
	rk3328-roc-cc.dtb \

dtb-$(CONFIG_CPU_RK3358) += \
	rk3358-evb-ddr3-v10-linux.dtb \

dtb-$(CONFIG_CPU_RK3368) += \
	rk3368-808-evb.dtb \
	rk3368-evb-act8846.dtb \
	rk3368-geekbox.dtb \
	rk3368-lion-haikou.dtb \
	rk3368-orion-r68-meta.dtb \
	rk3368-px5-evb.dtb \
	rk3368-r88.dtb \
	rk3368-tablet.dtb \
	rk3368a-817-tablet.dtb \
	rk3368a-817-tablet-bnd.dtb \

dtb-$(CONFIG_CPU_RK3399) += \
	rk3399-evb.dtb \
	rk3399-evb-ind-lpddr4-android.dtb \
	rk3399-evb-ind-lpddr4-android-avb.dtb \
	rk3399-evb-ind-lpddr4-linux.dtb \
	rk3399-evb-ind-lpddr4-v13-android-avb.dtb \
	rk3399-ficus.dtb \
	rk3399-firefly.dtb \
	rk3399-puma-haikou.dtb \
	rk3399-sapphire.dtb \
	rk3399-sapphire-excavator.dtb \
	rk3399-sapphire-excavator-edp-avb.dtb \
	rk3399-sapphire-excavator-linux.dtb \
	rk3399-sapphire-excavator-lp4-linux.dtb \
	rk3399-tve1030g-avb.dtb \
	rk3399pro-evb-lp4-v11-linux.dtb \
	rk3399pro-evb-v10-linux.dtb \
	rk3399pro-evb-v11-linux.dtb \
	rk3399pro-evb-v14-linux.dtb

# dtb-$(CONFIG_CPU_RK3568) += \
# 	rk3566-box-demo-v10.dtb \
# 	rk3566-evb-mipitest-v10.dtb \
# 	rk3566-evb1-ddr4-v10.dtb \
# 	rk3566-evb1-ddr4-v10-linux.dtb \
# 	rk3566-evb1-ddr4-v10-lvds.dtb \
# 	rk3566-evb2-lp4x-v10.dtb \
# 	rk3566-evb2-lp4x-v10-edp.dtb \
# 	rk3566-evb2-lp4x-v10-eink.dtb \
# 	rk3566-evb2-lp4x-v10-i2s-mic-array.dtb \
# 	rk3566-evb2-lp4x-v10-linux.dtb \
# 	rk3566-evb2-lp4x-v10-pdm-mic-array.dtb \
# 	rk3566-evb3-ddr3-v10.dtb \
# 	rk3566-evb3-ddr3-v10-linux.dtb \
# 	rk3566-evb5-lp4x-v10.dtb \
# 	rk3566-rk817-eink.dtb \
# 	rk3566-rk817-eink-w6.dtb \
# 	rk3566-rk817-eink-w103.dtb \
# 	rk3566-rk817-tablet.dtb \
# 	rk3566-rk817-tablet-k108.dtb \
# 	rk3566-rk817-tablet-rkg11.dtb \
# 	rk3566-rk817-tablet-v10.dtb \
# 	rk3568-evb1-ddr4-v10.dtb \
# 	rk3568-evb1-ddr4-v10-linux.dtb \
# 	rk3568-evb1-ddr4-v10-linux-spi-nor.dtb \
# 	rk3568-evb2-lp4x-v10.dtb \
# 	rk3568-evb2-lp4x-v10-bt1120-to-hdmi.dtb \
# 	rk3568-evb4-lp3-v10.dtb \
# 	rk3568-evb5-ddr4-v10.dtb \
# 	rk3568-evb6-ddr3-v10.dtb \
# 	rk3568-evb6-ddr3-v10-linux.dtb \
# 	rk3568-evb6-ddr3-v10-rk628-bt1120-to-hdmi.dtb \
# 	rk3568-evb6-ddr3-v10-rk628-rgb2hdmi.dtb \
# 	rk3568-evb6-ddr3-v10-rk630-bt656-to-cvbs.dtb \
# 	rk3568-evb7-ddr4-v10.dtb \
# 	rk3568-iotest-ddr3-v10.dtb \
# 	rk3568-iotest-ddr3-v10-linux.dtb \
# 	rk3568-nvr-demo-v10.dtb \
# 	rk3568-nvr-demo-v10-linux.dtb \
# 	rk3568-nvr-demo-v10-linux-spi-nand.dtb \
# 	rk3568-nvr-demo-v12-linux.dtb \
# 	rk3568-nvr-demo-v12-linux-spi-nand.dtb \
# 	rk3566-lubancat1-n.dtb \
# 	rk3568-lubancat2.dtb \
# 	rk3568-lubancat2-io.dtb \
# 	rk3568-lubancat2-io-mipi.dtb \
# 	rk3568-lubancat2@_saradc_ch3=288.dtb \
# 	rk3568-lubancat2-io@_saradc_ch3=407.dtb \
# 	rk3568-lubancat2-io-mipi@_saradc_ch3=1024.dtb

# endif

dtb-$(CONFIG_CPU_RK3568) += \
	rk3566-lubancat-0.dtb \
	rk3566-lubancat-1.dtb \
	rk3566-lubancat-1h.dtb \
	rk3566-lubancat-1n.dtb \
	rk3566-lubancat-1io.dtb \
	rk3568-lubancat-2.dtb \
	rk3568-lubancat-2-v1.dtb \
	rk3568-lubancat-2-v2.dtb \
	rk3568-lubancat-2n.dtb \
	rk3568-lubancat-2io.dtb

endif

subdir-y	:= $(dts-dirs) overlay
