# SPDX-License-Identifier: GPL-2.0
ifeq ($(CONFIG_ARCH_ROCKCHIP), y)

dtbo-$(CONFIG_CPU_RK3568) += \
	rk356x-lubancat-csi0-sc132gs-overlay.dtbo \
	rk356x-lubancat-csi0-ov5647-overlay.dtbo \
	rk356x-lubancat-csi0-ov5648-overlay.dtbo \
	rk356x-lubancat-csi0-ov8858-overlay.dtbo \
	rk356x-lubancat-csi1-ov5648-overlay.dtbo \
	rk356x-lubancat-csi1-ov8858-overlay.dtbo \
	rk356x-lubancat-csi1-ov5647-overlay.dtbo \
	rk356x-lubancat-csi1-sc132gs-overlay.dtbo \
	rk356x-lubancat-gmac1-disabled-overlay.dtbo \
	rk356x-lubancat-i2c3-m0-overlay.dtbo \
	rk356x-lubancat-i2c3-m1-overlay.dtbo \
	rk356x-lubancat-i2c5-m0-overlay.dtbo \
	rk356x-lubancat-pcie2x1-disabled-overlay.dtbo \
	rk356x-lubancat-pwm3-ir-overlay.dtbo \
	rk356x-lubancat-pwm7-ir-overlay.dtbo \
	rk356x-lubancat-pwm8-m0-overlay.dtbo \
	rk356x-lubancat-pwm9-m0-overlay.dtbo \
	rk356x-lubancat-pwm10-m0-overlay.dtbo \
	rk356x-lubancat-pwm11-ir-m0-overlay.dtbo \
	rk356x-lubancat-pwm12-m1-overlay.dtbo \
	rk356x-lubancat-pwm13-m1-overlay.dtbo \
	rk356x-lubancat-pwm14-m0-overlay.dtbo \
	rk356x-lubancat-pwm14-m1-overlay.dtbo \
	rk356x-lubancat-pwm15-ir-m0-overlay.dtbo \
	rk356x-lubancat-pwm15-ir-m1-overlay.dtbo \
	rk356x-lubancat-spi3-m1-overlay.dtbo \
	rk356x-lubancat-spi3-m1-gpio-cs-overlay.dtbo \
	rk356x-lubancat-uart3-m0-overlay.dtbo \
	rk356x-lubancat-uart3-m1-overlay.dtbo \
	rk356x-lubancat-uart4-m1-overlay.dtbo \
	rk356x-lubancat-uart5-m1-overlay.dtbo \
	rk356x-lubancat-uart7-m1-overlay.dtbo \
	rk356x-lubancat-uart8-m0-overlay.dtbo \
	rk356x-lubancat-uart8-m1-overlay.dtbo \
	rk356x-lubancat-uart9-m1-overlay.dtbo \
	rk3566-lubancat-0-spi3-m1-gpio-cs-overlay.dtbo \
	rk3566-lubancat-1h-edp-in-vp0-overlay.dtbo \
	rk3566-lubancat-1h-lvds-10.1-in-vp0-overlay.dtbo \
	rk3566-lubancat-1h-lvds-edp-touch-overlay.dtbo \
	rk3566-lubancat-1io-dsi0-in-vp0-7.0-1024x600-overlay.dtbo \
	rk3566-lubancat-1io-dsi0-in-vp0-10.1-800x1280-overlay.dtbo \
	rk3566-lubancat-1io-dsi0-in-vp0-1080p-overlay.dtbo \
	rk3566-lubancat-1io-dsi0-in-vp0-rpi-overlay.dtbo \
	rk3566-lubancat-1io-dsi1-in-vp0-7.0-1024x600-overlay.dtbo \
	rk3566-lubancat-1io-dsi1-in-vp0-10.1-800x1280-overlay.dtbo \
	rk3566-lubancat-1io-dsi1-in-vp0-1080p-overlay.dtbo \
	rk3566-lubancat-1io-dsi1-in-vp0-rpi-overlay.dtbo \
	rk3566-lubancat-1io-edp-in-vp0-overlay.dtbo \
	rk3566-lubancat-1io-edp-touch-overlay.dtbo \
	rk3566-lubancat-dsi0-7.0-1024x600-overlay.dtbo \
	rk3566-lubancat-dsi0-10.1-800x1280-overlay.dtbo \
	rk3566-lubancat-dsi0-720p-overlay.dtbo \
	rk3566-lubancat-dsi0-1080p-overlay.dtbo \
	rk3566-lubancat-dsi0-rpi-overlay.dtbo \
	rk3566-lubancat-msata-overlay.dtbo \
	rk3568-lubancat-2-dsi0-in-vp1-7.0-1024x600-overlay.dtbo \
	rk3568-lubancat-2-dsi0-in-vp1-10.1-800x1280-overlay.dtbo \
	rk3568-lubancat-2-dsi0-in-vp1-1080p-overlay.dtbo \
	rk3568-lubancat-2-dsi0-in-vp1-rpi-overlay.dtbo \
	rk3568-lubancat-2-dsi1-in-vp0-7.0-1024x600-overlay.dtbo \
	rk3568-lubancat-2-dsi1-in-vp0-10.1-800x1280-overlay.dtbo \
	rk3568-lubancat-2-dsi1-in-vp0-1080p-overlay.dtbo \
	rk3568-lubancat-2-dsi1-in-vp0-rpi-overlay.dtbo \
	rk3568-lubancat-2io-edp-in-vp1-overlay.dtbo \
	rk3568-lubancat-can1-m0-overlay.dtbo \
	rk3568-lubancat-can1-m1-overlay.dtbo \
	rk3568-lubancat-can2-m0-overlay.dtbo \
	rk3568-lubancat-canfd1-m0-overlay.dtbo \
	rk3568-lubancat-canfd1-m1-overlay.dtbo \
	rk3568-lubancat-canfd2-m0-overlay.dtbo \
	rk3568-lubancat-dsi0-7.0-1024x600-overlay.dtbo \
	rk3568-lubancat-dsi0-10.1-800x1280-overlay.dtbo \
	rk3568-lubancat-dsi0-720p-overlay.dtbo \
	rk3568-lubancat-dsi0-1080p-overlay.dtbo \
	rk3568-lubancat-dsi0-rpi-overlay.dtbo \
	rk3568-lubancat-edp-touch-overlay.dtbo \
	rk3568-lubancat-hdmi-disabled-overlay.dtbo \
	rk3568-lubancat-msata-overlay.dtbo
	

endif

scr-$(CONFIG_ARCH_ROCKCHIP) += \
	rockchip-fixup.scr

dtbotxt-$(CONFIG_ARCH_ROCKCHIP) += \
	README.rockchip-overlays.md

targets += $(dtbo-y) $(scr-y) $(dtbotxt-y)

always			:= $(dtbo-y) $(scr-y) $(dtbotxt-y)
clean-files		:= *.dtbo *.scr

